// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: lma.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Rating_RatingType int32

const (
	Rating_RATING_UNKNOWN  Rating_RatingType = 0
	Rating_RATING_BEATS    Rating_RatingType = 1
	Rating_RATING_PASTORAL Rating_RatingType = 2
	Rating_RATING_OVERALL  Rating_RatingType = 3
)

// Enum value maps for Rating_RatingType.
var (
	Rating_RatingType_name = map[int32]string{
		0: "RATING_UNKNOWN",
		1: "RATING_BEATS",
		2: "RATING_PASTORAL",
		3: "RATING_OVERALL",
	}
	Rating_RatingType_value = map[string]int32{
		"RATING_UNKNOWN":  0,
		"RATING_BEATS":    1,
		"RATING_PASTORAL": 2,
		"RATING_OVERALL":  3,
	}
)

func (x Rating_RatingType) Enum() *Rating_RatingType {
	p := new(Rating_RatingType)
	*p = x
	return p
}

func (x Rating_RatingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rating_RatingType) Descriptor() protoreflect.EnumDescriptor {
	return file_lma_proto_enumTypes[0].Descriptor()
}

func (Rating_RatingType) Type() protoreflect.EnumType {
	return &file_lma_proto_enumTypes[0]
}

func (x Rating_RatingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rating_RatingType.Descriptor instead.
func (Rating_RatingType) EnumDescriptor() ([]byte, []int) {
	return file_lma_proto_rawDescGZIP(), []int{2, 0}
}

type Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The readable name of the label
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Discogs id of the label
	DiscogsId int32 `protobuf:"varint,2,opt,name=discogs_id,json=discogsId,proto3" json:"discogs_id,omitempty"`
}

func (x *Label) Reset() {
	*x = Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lma_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_lma_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_lma_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetDiscogsId() int32 {
	if x != nil {
		return x.DiscogsId
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the record
	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	DiscogsId int32  `protobuf:"varint,2,opt,name=discogs_id,json=discogsId,proto3" json:"discogs_id,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lma_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_lma_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_lma_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Record) GetDiscogsId() int32 {
	if x != nil {
		return x.DiscogsId
	}
	return 0
}

type Rating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  Rating_RatingType `protobuf:"varint,1,opt,name=type,proto3,enum=lma.Rating_RatingType" json:"type,omitempty"`
	Score float32           `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Rating) Reset() {
	*x = Rating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lma_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_lma_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_lma_proto_rawDescGZIP(), []int{2}
}

func (x *Rating) GetType() Rating_RatingType {
	if x != nil {
		return x.Type
	}
	return Rating_RATING_UNKNOWN
}

func (x *Rating) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_lma_proto protoreflect.FileDescriptor

var file_lma_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6c, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x6d, 0x61,
	0x22, 0x3a, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x67, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x67, 0x73, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x67, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x67, 0x73, 0x49, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x06,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6c, 0x6d, 0x61, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x5b, 0x0a, 0x0a, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x41, 0x54, 0x49, 0x4e, 0x47,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x41,
	0x54, 0x49, 0x4e, 0x47, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x53, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x52, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x41, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x4c, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x56, 0x45, 0x52,
	0x41, 0x4c, 0x4c, 0x10, 0x03, 0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lma_proto_rawDescOnce sync.Once
	file_lma_proto_rawDescData = file_lma_proto_rawDesc
)

func file_lma_proto_rawDescGZIP() []byte {
	file_lma_proto_rawDescOnce.Do(func() {
		file_lma_proto_rawDescData = protoimpl.X.CompressGZIP(file_lma_proto_rawDescData)
	})
	return file_lma_proto_rawDescData
}

var file_lma_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lma_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lma_proto_goTypes = []interface{}{
	(Rating_RatingType)(0), // 0: lma.Rating.RatingType
	(*Label)(nil),          // 1: lma.Label
	(*Record)(nil),         // 2: lma.Record
	(*Rating)(nil),         // 3: lma.Rating
}
var file_lma_proto_depIdxs = []int32{
	0, // 0: lma.Rating.type:type_name -> lma.Rating.RatingType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lma_proto_init() }
func file_lma_proto_init() {
	if File_lma_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lma_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lma_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lma_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lma_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lma_proto_goTypes,
		DependencyIndexes: file_lma_proto_depIdxs,
		EnumInfos:         file_lma_proto_enumTypes,
		MessageInfos:      file_lma_proto_msgTypes,
	}.Build()
	File_lma_proto = out.File
	file_lma_proto_rawDesc = nil
	file_lma_proto_goTypes = nil
	file_lma_proto_depIdxs = nil
}
